### ISSUE TITLE
Linker error on MSVC

### ISSUE THREAD

**Issue by Rookfighter** [build2-packaging/FTXUI#1]
@boris-kolpackov 

I keep getting this linker error on MSVC, however I can't figure out what the problem is. Any ideas? Did I model dependencies wrong in some place?

```
LINK : fatal error LNK1181: cannot open input file 'libftxui-3.0.0-a.0.20230125073955.79530aaad9da\src\ftxui-screen.dll.lib'
```

bdep ci build is available here:

https://ci.cppget.org/@8e22081b-3760-4ed3-850e-cf9355b1c70e

**Comment by boris-kolpackov** [comment]
This most likely means that no symbols were exported from the DLL, in which case `link.exe` "helpfully" omits creating the import library. We've actually added detection/proper diagnostics for this in the upcoming 0.16.0. You could try to CI on stage (`bdep ci --server https://ci.stage.build2.org ...`) and see if it clarifies things.

**Comment by Rookfighter** [comment]
Thanks, that hint gave me the right direction :+1: The library does not define any `EXPORT` macros for windows, so I had to limit the windows build to static only (similar as in the `jsonxx` package).

**Comment by boris-kolpackov** [comment]
You could also try the auto-export support: https://build2.org/build2/doc/build2-build-system-manual.xhtml#cc-auto-symexport

It works quite well provided you don't need to export any global variables, only functions.
