### ISSUE TITLE
Few issues with submitted 3.0.0 packages

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/FTXUI#2]
While reviewing the submitted packages I've noticed the following mostly minor issues:

1. `libftxui/{include,src}/buildfile`: `{ixx hxx}{*}:` -- the library doesn't use inline files so `ixx` should probably be dropped.

    Or, alternatively, assign the extension to the `ixx` target type (like you do in `-examples`). Seeing that they use an inline file in example, maybe this is a better option since upstream may add `.ipp` files to the main library in the future. Also in the `-tests` package.

2. `libftxui/src/buildfile`: stray/unused `src_inc_dirs` variable.

3. `libftxui/src/buildfile`: `/utf-8` MSVC option is the default.

4. `libftxui/src/buildfile`:

   ```
   lib{ftxui-screen}: bin.lib.version = "-$version.project_id"
   lib{ftxui-dom}: bin.lib.version = "-$version.project_id"
   lib{ftxui-component}: bin.lib.version = "-$version.project_id"
   ```
   
   This (and in the `else` block) can be shortened as:
   
   ```
   lib{ftxui-screen ftxui-dom ftxui-component}: bin.lib.version = "-$version.project_id"
   ```
 
 5. There is an export stub in `-examples` which I don't believe is needed. There is also one in `-tests` but this package appears to be building a library so maybe I am missing something here.
 
 6. `libftxui-tests/src/` appears to be missing the `ftxui/` subdirectory. I believe the reason is that you need a recursive wildcard (`**`) here:
 
    ```
    lib{ftxui-tests}: {hxx cxx}{*_test}
    ```
    
    Also it's a bit strange that it only builds the library, but perhaps you know something that I don't. Maybe add a comment on what's going on here?
    
But otherwise nicely done, thanks for your work! I think all of these are very minor except for 6 which probably warrants a revision. So I will hold off on publishing this.

**Comment by Rookfighter** [comment]
Thanks for the feedback! I'll fix these issues ASAP. :+1:

**Comment by Rookfighter** [comment]
@boris-kolpackov 

I fixed most of the issues you found. There were some really stupid copy and paste mistakes among them :see_no_evil: Sorry about that. `ftxui-tests` is now a proper executable and I also marked it as test (in `root.build`). Also removed the export stubs. 
Regarding point 3. What do you mean /utf-8 is the default? Should I drop it because it's implicitly there anyway? I actually added it because I mimic the cmake build files of the upstream.

**Comment by boris-kolpackov** [comment]
> What do you mean `/utf-8` is the default? 

I mean from 0.15.0 we pass this option by default: https://github.com/build2/build2/blob/master/NEWS#L116-L127

So I would just drop it.

**Comment by Rookfighter** [comment]
New revision submitted. I think I fixed all of the mentioned issues. I had a problem with a failing unit test on windows (which is a upstream problem), so I just excluded that test for windows builds.

**Comment by boris-kolpackov** [comment]
> New revision submitted. I think I fixed all of the mentioned issues.

Published, thanks!

> I had a problem with a failing unit test on windows (which is a upstream problem), so I just excluded that test for windows builds.

If this is something that is likely to be fixed by upstream I personally don't bother disabling failing tests since it's hard to remember to re-enable them on upgrades later.
